# Generated by Django 4.1.4 on 2023-05-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email2',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='name2',
        ),
    ]
