# Generated by Django 4.1.4 on 2023-05-19 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Complex', 'Complex')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
